package sttp.openai.requests.completions.chat

import sttp.openai.json.SnakePickle

/** @param id
  *   Unique identifier for this audio response.
  * @param expiresAt
  *   The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn
  *   conversations.
  * @param data
  *   Base64 encoded audio bytes generated by the model, in the format specified in the request.
  * @param transcript
  *   Transcript of the audio generated by the model.
  */
case class Audio(
    id: String,
    expiresAt: Int,
    data: String,
    transcript: String
)

object Audio {
  implicit val audioR: SnakePickle.Reader[Audio] = SnakePickle.macroR[Audio]
}
