package sttp.openai.requests.completions.chat

import sttp.openai.json.SnakePickle

/** @param arguments
  *   The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid
  *   JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your
  *   function.
  * @param name
  *   The name of the function to call.
  */
case class FunctionCall(arguments: String, name: String)

object FunctionCall {
  implicit val functionCallRW: SnakePickle.ReadWriter[FunctionCall] = SnakePickle.macroRW[FunctionCall]
}
